server {

    listen 8128;

    server_name timur.sevima.site;

    root /var/www/timur;

    index index.html;

    add_header X-Owner-By "Muhammad Anjas A";
    add_header X-Served-By "Nginx";

    location / {
        try_files $uri $uri/ =404;
    }

    access_log /var/log/nginx/timur_access.log;
    error_log  /var/log/nginx/timur_error.log;

}
